glyphs = {
    'death_knight': frozenset([]),
    'druid': frozenset([]),
    'hunter': frozenset([]),
    'mage': frozenset([]),
    'monk': frozenset([]),
    'paladin': frozenset([]),
    'priest': frozenset([]),
    'rogue': frozenset([
        # Major
        'adrenaline_rush',
        'ambush',
        'blade_flurry',
        'blind',
        'cheap_shot',
        'cloak_of_shadows',
        'crippling_poison',
        'deadly_momentum',
        'debilitation',
        'evasion',
        'expose_armor',
        'feint',
        'garrote',
        'gouge',
        'kick',
        'recuperate',
        'sap',
        'shadow_walk',
        'shiv',
        'smoke_bomb',
        'sprint',
        'stealth',
        'vanish',
        'vendetta',
        # Minor
        'blurred_speed',
        'decoy',
        'detection',
        'disguise',
        'distract',
        'hemorrhage',
        'killing_spree',
        'pick_lock',
        'pick_pocket',
        'poisons',
        'safe_fall',
        'tricks_of_the_trade',
    ]),
    'shaman': frozenset([]),
    'warlock': frozenset([]),
    'warrior': frozenset([]),
}
